[app]
port = 8080

[database]
host = "localhost"
name = "test"
user = "test"
password = "test"
port = 3306

[oss]
access_key_id = ""
access_key_secret = ""
region = ""
end_point = ""
bucket = ""

[redis]
ip = "localhost"
port = 6379